# Generated by Django 2.1.15 on 2022-10-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221030_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Composer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyricist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Lyricist'),
        ),
    ]
