# Generated by Django 2.1.15 on 2022-10-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221030_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imageThumb',
            field=models.ImageField(upload_to='movieThumb'),
        ),
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Movie'),
        ),
    ]
